# Generated by Django 4.2.7 on 2026-09-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_added', 'Credits Added'), ('sms_sent', 'SMS Sent'), ('payment_received', 'Payment Received')], max_length=30)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='schools.school')),
            ],
            options={
                'db_table': 'notifi_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='schools.school')),
            ],
            options={
                'db_table': 'notifi_templates',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender_id_used', models.CharField(max_length=20)),
                ('group_name_snapshot', models.CharField(max_length=100)),
                ('recipient_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('partial', 'Partially Sent')], default='pending', max_length=20)),
                ('beem_request_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contactgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schools.school')),
            ],
            options={
                'db_table': 'notifi_messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
