# Generated by Django 4.2.7 on 2026-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('sms_balance', models.IntegerField(default=0)),
                ('sender_id', models.CharField(blank=True, max_length=11)),
                ('sender_id_status', models.CharField(choices=[('none', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifi_schools',
                'ordering': ['-created_at'],
            },
        ),
    ]
